slime-io/slime

slime-boot/helm-charts/slimeboot/templates/cluster-globalsidecar.yaml
slime-boot/helm-charts/slimeboot/templates/namespaced-globalsidecar.yaml
slime-boot/helm-charts/slimeboot/values.yaml

[Configuration Lazy Loading] Feature: Support cluster global-sidecar

---

README.md
README_ZH.md

update readme shell scripts and yaml version

update readme shell scripts and yaml version

---

slime-boot/helm-charts/slimeboot/templates/cluster-globalsidecar.yaml
slime-boot/helm-charts/slimeboot/templates/namespaced-globalsidecar.yaml

Apply globalSidecar envoyfilter dispatches field to namespaced part

---

doc/en/lazy_load.md
doc/zh/lazy_load.md
install/samples/lazyload/slimeboot_lazyload.yaml

Update global pilot image to fix build-listeners low performance

---

slime-framework/controllers/controller.go
slime-modules/lazyload/controllers/process.go
slime-modules/lazyload/controllers/servicefence_controller.go
slime-modules/lazyload/main.go

Fence supports auto-gen cr based on ns/svc label

---

doc/en/lazy_load.md
doc/zh/lazy_load.md

Fence add doc to describe custom-dispatch-traffic feature

---

bin/publish.sh
slime-boot/helm-charts/slimeboot/templates/cluster-globalsidecar.yaml
slime-boot/helm-charts/slimeboot/templates/pilot.yaml
slime-boot/publish.sh

Move cluster-level to-global-sidecar envoyfilter to istio-system ns to make it work

Move cluster-level to-global-sidecar envoyfilter to istio-system ns

---

Makefile

`make -f ../slime/Makefile  generate`    =>    update deepcopy
`make -f ../slime/Makefile  manifests`  =>  update crds

support auto generate deepcopy and crds

---

framework/model/module/module.go

In the previous version, the config file of the framework layer contains the config type of modules, like below. 
```protobuf
message Config {
Plugin plugin = 1;
Limiter limiter = 2;
Global global = 3;
Fence fence = 4;
// ...
}
```
This means changes to the module configuration fields have to be implemented by changing the framework level configuration file, like this https://github.com/slime-io/slime/pull/135, which is certainly very inappropriate. 
Now we can use `general` field of framework config to fill module config. For example, we can use `config.general` to tranfer `wormholePort` to lazyload module instead of use `config.fence` anymore.
```json
{
"fence": {
"wormholePort": [
"9090"
]
}
}
{
"general": {
"wormholePort": [
"9090"
]
}
}
```

Support getting module config from slimeboot general field

---

bin/publish.sh
framework/model/metric/accesslog_convertor.go
framework/model/metric/config.go
framework/model/metric/watcher_producer.go

The value comes from existed servicefences.

AccessLogSource adds param for cache init

---

boot/publish.sh
framework/model/module/module.go

- Fix publish slime-boot image script error
- Module general config allow unknown fields

Fix some errors for module general config

---

framework/util/const.go

Signed-off-by: believening <kang_417@yeah.net>

fix wrong plugin name refer to envoy api

---

staging/src/slime.io/slime/modules/plugin/README.md
staging/src/slime.io/slime/modules/plugin/README_zh.md

add more usage example for plugin module

plugin: update readme

---

staging/src/slime.io/slime/modules/lazyload/charts/charts.go
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go
staging/src/slime.io/slime/modules/lazyload/controllers/update_resources.go

to resolve https://github.com/slime-io/slime/issues/199#issuecomment-1296600033.
after this, We have the ability to start the lazyload module without slimeboot deploy.

lazyload: support get slimeboot cr by labelselector

---

framework/bootstrap/config.go
framework/model/config.go
staging/src/slime.io/slime/modules/lazyload/controllers/process.go
staging/src/slime.io/slime/modules/lazyload/controllers/servicefence_controller.go
staging/src/slime.io/slime/modules/limiter/controllers/process.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go
staging/src/slime.io/slime/modules/plugin/controllers/envoyplugin_controller.go
staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go

slime module will manage resource in  istioRev and configRev if not empty

merge configRev and istioRev to manage resource

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml

due to: https://github.com/istio/istio/pull/19864

lazyload: disable timeout for cluster global-sidecar

---

doc/zh/slime-build.md
staging/src/slime.io/slime/modules/lazyload/cmd/proxy/publish.sh

update publish.sh to build mulit-arch global-sidecar
usage:
```shell
cd slime/staging/src/slime.io/slime/modules/lazyload/cmd/proxy
./publish.sh publish arm64 amd64
```

update publish.sh and make it easy to build global-sidecar

---

bin/multiarch.sh
bin/publish.sh
staging/src/slime.io/slime/modules/bundle-hango/Dockerfile
staging/src/slime.io/slime/modules/lazyload/Dockerfile
staging/src/slime.io/slime/modules/lazyload/cmd/proxy/Dockerfile
staging/src/slime.io/slime/modules/lazyload/publish.sh
staging/src/slime.io/slime/modules/limiter/Dockerfile
staging/src/slime.io/slime/modules/limiter/publish.sh
staging/src/slime.io/slime/modules/plugin/Dockerfile
staging/src/slime.io/slime/modules/plugin/publish.sh

usage: build lazyload amd image
``` shelll
cd staging/src/slime.io/slime/modules/lazyload
BASE_IMAGE=ubuntu:bionic ./publish.sh build image
```

add BASE_IMAGE to change base image

---

framework/go.mod
framework/model/module/module.go
framework/model/pkg/leaderelection/kubeleaderelector.go
framework/model/pkg/leaderelection/leaderelector.go
staging/src/slime.io/slime/modules/lazyload/module/module.go
staging/src/slime.io/slime/modules/limiter/module/module.go
staging/src/slime.io/slime/modules/plugin/module/module.go

the framework supports leader election, which in turn supports #216.

framework: support leader election

---

framework/go.mod
framework/go.sum
framework/model/module/module.go

call wg.Add(1) before starting the goroutine to avoid a race

framework: fix race of waitgroup

---

framework/model/module/module.go

Since the `mgr` will exit if the election fails, we adjust the life cycle of `le` to be consistent with the `mgr`.

framework: add more info about leader election

---

staging/src/slime.io/slime/modules/lazyload/controllers/process.go
staging/src/slime.io/slime/modules/lazyload/controllers/producer.go
staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go
staging/src/slime.io/slime/modules/lazyload/controllers/servicefence_controller.go
staging/src/slime.io/slime/modules/lazyload/module/module.go

refactor lazyload to adapt to the framework election framework

lazyload: support leader election

---

framework/model/pkg/leaderelection/kubeleaderelector.go

locked by `RLock` but call `Unlock` when unlock.

framework: fix panic when trigger onStoppedLeading

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/controllers/servicefence_controller.go

set lazyload-accesslog-source address from global.slimeNamespace

change lazyload grpc address in template file

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml

relate issue https://github.com/slime-io/slime/issues/211

fix: dispatch domains in template file

---

staging/src/slime.io/slime/modules/meshregistry/go.mod
staging/src/slime.io/slime/modules/meshregistry/go.sum
staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

refactor watching mode impl of zk source.

meshregistry: refactor watching mode of zk source

---

staging/src/slime.io/slime/modules/bundle-hango/go.mod
staging/src/slime.io/slime/modules/bundle-hango/go.sum
staging/src/slime.io/slime/modules/meshregistry/go.mod
staging/src/slime.io/slime/modules/meshregistry/go.sum

fix build meshregistry alone failed

meshregistry: replace go zk to slime fork

---

staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go

fix https://github.com/slime-io/slime/issues/265

plugin: fix handleSecretChange assign to nil map

---

framework/bootstrap/configcontroller.go

An initial improvement, subsequent content will need to rely on pr https://github.com/slime-io/slime/pull/251

startXdsMonitorController not wait for data sync

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go

meshregistry: fix debug api for nacos cache not working

---

staging/src/slime.io/slime/modules/lazyload/controllers/process.go

we start a ticker at 10 second intervals, generating metrics for each servicefence. Refresh based on metrics should be skipped when there is no change in the metrics.
resolve #275

lazyload: skip refresh when metric result has not changed

---

staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go

给a服务下发
```
metadata:
name: a
namespace: default
spec:
sets:
_base:
descriptor:
- action:
fill_interval:
seconds: 10
quota: "2"
strategy: "single"
target:
port: 9080
```
之间不做任何变动，立刻给b下发相同配置
```
metadata:
name: b
namespace: default
spec:
sets:
_base:
descriptor:
- action:
fill_interval:
seconds: 10
quota: "2"
strategy: "single"
target:
port: 9080
```
b 不会生效

fix: limiter not take effect by lastUpdatePolicy

---

staging/src/slime.io/slime/modules/meshregistry/pkg/util/validation.go

usage:
1. add env to slime pod 
```yaml
- name: SE_LABEL_SELECTOR_KEYS
value: app,k8sNs:myNs,$host:myHost
```
2. we can see relevant labels in the generated serviceentries
```yaml
"type": "networking.istio.io/v1alpha3/ServiceEntry",
"name": "nsf-demo-stock-provider-grpc.skiff-nsfdemo-agent",
"namespace": "skiff-nsfdemo-agent",
"labels": {
"myHost": "nsf-demo-stock-provider-grpc.skiff-nsfdemo-agent.svc.cluster.local",
"myNs": "skiff-nsfdemo-agent",
},
"Spec": {
"hosts": [
"nsf-demo-stock-provider-grpc.skiff-nsfdemo-agent.svc.cluster.local"
],
```

meshregistry: SE_LABEL_SELECTOR_KEYS supports pick se meta via $-prefixed key

---

framework/model/metric/accesslog_source.go
framework/model/metric/mock_source.go
framework/model/metric/model.go
framework/model/metric/producer.go
framework/model/metric/prometheus_source.go
staging/src/slime.io/slime/modules/lazyload/controllers/process.go
staging/src/slime.io/slime/modules/lazyload/module/module.go
staging/src/slime.io/slime/modules/lazyload/pkg/server/http.go
staging/src/slime.io/slime/modules/limiter/module/module.go

parameters ns is needed
1. reset productpage in default
```
curl 'xxx:8081/lazylaod/debug/svfReset?ns=default&svc=productpage'
```
2. reset all svf in default
```
curl 'xxx:8081/lazyload/debug/svfReset?ns=default'
```

lazyload: support svf reset

---

staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go

lazyload 目前不支持grpc, 但之前又将grpc端口纳管了进来
并且我们不需要统计除了http以外的任何端口信息。

lazyload: delete grpc port from wormPort

---

staging/src/slime.io/slime/modules/meshregistry/module/module.go

The dynamically generated configurations in large-scale service data scenarios may be large enough to exceed the maximum storage capacity of configmap, making it impossible to issue dynamic configurations. 
The meshreg configuration parameters provide many runtime modification APIs for individual services and even individual instances. These APIs are mainly centered around the service name, which means that there will be a lot of repeated strings in the configuration. Compressing the configuration and saving it in configmap can increase the upper limit of the dynamic configuration size. 
Testing shows that the compression rate of the original dynamic configuration using gzip is around 10%, and supporting gzip compression can increase the upper limit of the dynamic configuration size by …

meshreg: support load gzip compressed dynamic configmap

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

If the first watch fails, the returned event channel is `nil`, but we do wait on the channel, which causes our goroutine to hang.

meshreg: fix causing hang when ep watcher failed to make first watch

---

boot/helm-charts/slimeboot/templates/deployment.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml

fix wrong default value about enableLeaderElection in chart

---

staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

**背景**
目前istio对wasm的支持会在pilot-agent中做远程插件到本地插件的转换，这个过程不具备最终一致性，也即 如果获取远程插件的过程中网络抖动一下获取失败的话，会导致envoy xds配置不可用，并且没有主动纠错、恢复机制。
同时，ECDS下发的插件不可用时带来的影响不只是配置拒绝，还会影响当前插件链的正常工作，也即影响业务请求处理。
所以有必要提高容错性： 通过ECDS的default config字段来做插件降级，让最坏情况的影响仅仅是插件本身无效。
**设计**
增加plugin module配置字段 `map<string, google.protobuf.Struct> configDiscoveryDefaultConfig`，用于配置不同插件类型的默认配置，key为 type url。 
以rider为例，配置如下：
```yaml
configDiscoveryDefaultConfig:
"type.googleapis.com/proxy.filters.http.rider.v3alpha1.FilterConfig":
'@type': type.googleapis.com/udpa.type.v1.TypedStruct
type_url: type.googleapis.com/proxy.filters.http.rider.v3alpha1.FilterConfig
value:
plugin:
code:
local:
inline_string: |
local test = {}
return test
name: test
vm_config:
package_path: /usr/local/lib/rider/?/init.lua;/usr/local/lib/rider/?.lua;
``` …

plugin: wasm/rider plugin support default config

---

staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

背景： wasm不允许configuration为空，envoy可能拒绝ecds配置，甚至crash。
应对： 参考[istio的例子](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) 可以在settings/configuration为空时，设置默认值 `{}` 来work around：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
name: wasm-example
namespace: myns
spec:
configPatches:
- applyTo: EXTENSION_CONFIG
patch:
operation: ADD # REPLACE is also supported, and would override a cluster level resource with the same name.
value:
name: my-wasm-extension
typed_config:
"@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
config:
root_id: my-wasm-root-id
vm_config:
vm_id: my-wasm-vm-id
runtime: envoy.wasm.runtime.v8
code:
remote:
http_uri:
uri: http://my-wasm-binary-uri
configuration:
"@type": …
```

plugin: wasm plugin use default '{}' when settings nil

---

staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go

cache not ready endpoint address 

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go
staging/src/slime.io/slime/modules/limiter/model/const.go

relate: https://github.com/slime-io/slime/pull/418

limiter: support bodymatch with headermatch within group

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_filters.go
staging/src/slime.io/slime/modules/limiter/controllers/producer.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go

支持根据 workloadselector 选择pods，计算pods数量

limiter: support average by workloadselector

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go

兼容老参数
问题引入: https://github.com/slime-io/slime/pull/418 https://github.com/slime-io/slime/pull/427

limiter: fix compatible problem about useQueryMatch

---

staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go

在 https://github.com/slime-io/slime/pull/422 优化中
在启动时，lazyload用list获取全量svc port，如果此时通过watch 方式也获取了全量port
这就会导致两者判断相等，不更新envoyfilter
解决方式，在启动后的第一次更新中，触发updateResource

lazyload: fix not update resource when StartAutoPort at begining

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go

meshreg: sync the tenant isolation logic under the gateway mode from Eureka to Nacos

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

The reconnect logic is written in both the `meshregistry` and `go-zk` and runs in different goroutines.
The `go-zk` reconnect relies on `meshregsitry` calling `zk.Conn.Close` to terminate the reconnect, but there is no synchronization mechanism between the two.
If `go-zk` do reconnect before the `Close` call, it will cause the `meshregsitry` to be triggered to reconnect again after the `Close` call, which in turn will cause the `zk.Conn` created by the previous `meshregsitry` reconnect to be closed and triggered to reconnect again and again.
We've made two improvements for this:
1. Skip triggering `meshregistry` reconnect if `go-zk` reconnects successfully before triggering `meshregistry` reconnect.
2. Since `meshregistry` reconnect creates a new `zk.Conn`, we require that each `zk.Conn` …

meshreg: fix repeat trigger zk reconnect

---

framework/util/const.go
staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

```yaml
patch:
operation: MERGE
value:
metadata:
typedFilterMetadata:
gateway-system.url-xxx:
'@type': type.googleapis.com/google.protobuf.StringValue
value: '{"xx": "yy"}'
```

plugin: envoyplugin mv wasm plugin config to typedFilterMetadata

---

framework/util/const.go
staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

This reverts commit 38f9589401d55f5c9dbc6e5281a9a6f22c3495a9.

Revert "plugin: envoyplugin mv wasm plugin config to typedFilterMetadata"

---

staging/src/slime.io/slime/modules/bundle-all/go.mod
staging/src/slime.io/slime/modules/bundle-all/go.sum
staging/src/slime.io/slime/modules/bundle-hango/go.mod
staging/src/slime.io/slime/modules/bundle-hango/go.sum
staging/src/slime.io/slime/modules/meshregistry/go.mod
staging/src/slime.io/slime/modules/meshregistry/go.sum
staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

1. watching 支持  resync，补偿事件丢失
2. 全量更新时做打散处理，避免流量集中
3. 对于频繁快速变化zk节点，提供防抖配置

Optimize zk watch mode

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_filters.go

支持在一个限流action中，配置多个ip限流，ip间为or关系

limiter: support add multi ips in one atcions

---

framework/util/const.go
staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go

related: https://github.com/slime-io/slime/pull/473

limiter: add missing value{} in enableRatelimitPlaceholderInRoute

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

meshreg: handing of consumers-only change events

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_global_limit.go

limiter: fix missing metadata when updating rls configmap

---

framework/util/proto.go
staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go

import from:  https://github.com/slime-io/slime/pull/427. https://github.com/slime-io/slime/pull/468
gogoproto 对长度为零的非空切片执行序列化时，会保留字段，golang proto 不会，导致生成  json-body match 失败。

limiter: fix missing route patch when only configuring json_body match

---

staging/src/slime.io/slime/modules/meshregistry/pkg/multicluster/multicluster.go
staging/src/slime.io/slime/modules/meshregistry/pkg/server/processing.go
staging/src/slime.io/slime/modules/meshregistry/pkg/util/cache/cache.go
staging/src/slime.io/slime/modules/meshregistry/pkg/util/cache/nodeCache.go
staging/src/slime.io/slime/modules/meshregistry/pkg/util/cache/podCache.go

start source after informer has synced when enable cluster cache

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/httpclient.go

nacos 注册中心自带了 namespace 和 group 等隔离概念，这些特性已经被用户在实际生产中使用，我们在 https://github.com/slime-io/slime/pull/293 中支持获取全部 namespace 内全部 group 的服务及其实例的能力，对于需要更细粒度获取多 namespace 多 group 来说就不合适了。
为此 pr 提供了新的配置 api `NacosServer.NamespaceGroups` 用于配置从指定多个  namespace 及其 group 中获取实例，api详情见代码及其注释。示例如下：
```
Nacos:
NamespaceGroups:
- ns1:g1
- ns2:g1,g2
- public
```
至此对于 nacos 注册中心提供了三种方式配置服务源（优先级从高到低）：
- `NacosServer.AllNamespaces`：bool 型，获取全部 ns 内全部 group 的服务及其实例
- `NacosServer.NamespaceGroups`
- `NacosServer.Namespace` 和 `NacosServer.Group`
需要注意的是，不同 namespace 不同 group 下的同名服务会被聚合到一起，这个行为和 #293 保持一致。
---
此外，在配置指定 namespace 时，我们支持了从 nacos namespace `showname` 到 `namespaceId` 的自动映射，对于使用 nacos 自动生成 `namespaceId` 的场景更加友好。

meshreg: support for nacos multiple namespaces and multiple groups
