install/samples/lazyload/slimeboot_lazyload.yaml
install/samples/plugin/slimeboot_plugin.yaml
slime-modules/lazyload/main.go
slime-modules/plugin/main.go
test/e2e/testdata/install/samples/lazyload/slimeboot_lazyload.yaml

Fix error name of configmap for leader election, and build new image of lazyload and pluginmanager,  from v0.2.1 to v0.2.2.

Fix error name of configmap for leader election

---

framework/bootstrap/config.go
framework/controllers/context.go
framework/go.mod
framework/go.sum
framework/model/metric/config.go
framework/model/metric/model.go
framework/model/metric/producer.go
framework/model/metric/prometheus_source.go
framework/model/metric/ticker_producer.go
framework/model/metric/watcher_producer.go
framework/model/module/module.go
framework/model/trigger/ticker_trigger.go
framework/model/trigger/watcher_trigger.go

Provide prometheus source now and accesslog source later.
Provide k8s gvk watcher trigger and crontab kind ticker trigger.
Provide metric producer to send metric to reconciler inside module. Each producer contains a trigger and source. Provide 2 kinds of producer now:
- watcher producer: watcher trigger + prometheus source
- ticker producer: ticker trigger + prometheus source
Provide accesslog producer later.
The source module will handle QueryMap kind data (map[string][]Handler), and return Metric kind data (map[string][]Result). All sources module will obey the rule.

slime metric reconfiguration

---

boot/helm-charts/slimeboot/templates/cluster-globalsidecar.yaml
boot/helm-charts/slimeboot/templates/deployment.yaml
boot/helm-charts/slimeboot/templates/namespaced-globalsidecar.yaml
boot/helm-charts/slimeboot/values.yaml
framework/bootstrap/config.go
framework/go.mod
framework/go.sum
framework/model/metric/accesslog_convertor.go
framework/model/metric/accesslog_source.go
framework/model/metric/config.go
framework/model/metric/model.go
framework/model/metric/producer.go
framework/model/metric/prometheus_source.go
framework/model/metric/ticker_producer.go
framework/model/metric/watcher_producer.go
framework/model/trigger/ticker_trigger.go

1. add accesslog source, which can produce metric from access log grpc server
- Note: Inspired by [aeraki](https://github.com/aeraki-framework/aeraki) accesslog processing approach, for which we would like to express our gratitude.
2. unify prometheus source and access log as metric source
```yaml
type Source interface {
QueryMetric(queryMap QueryMap) (Metric, error)
Start() error
}

new metric source 

---

framework/model/metric/accesslog_convertor.go
framework/model/metric/config.go

compatibale with https://github.com/slime-io/lazyload/pull/14

the handler of accesslog convertor uses endpoints cache map

---

framework/bootstrap/config.go
framework/bootstrap/http.go
framework/model/module/module.go

Example:
Just add custom http handler in function `InitManager` of lazyload as following, then you have a new api interface `/lazyload/xxx`
```go
func (mo *Module) InitManager(mgr manager.Manager, env bootstrap.Environment, cbs module.InitCallbacks) error {
// register custom api interface
env.HttpPathHandler.Handle("xxx", livezHandler())
// ...
return nil
}
func livezHandler() http.Handler {
return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
if _, err := w.Write([]byte("Healthy!")); err != nil {
log.Errorf("livez probe error, %+v", err)
}
})
}

Support for adding custom http handlers in module level

---

framework/bootstrap/config.go
framework/go.mod
framework/go.sum
framework/model/module/module.go

In previous version, slime only supports json format module config, branched or non-branched json, like below
```json
{
"general": {
"wormholePort": [
"9080"
],
"namespace": [
"default",
"test"
]
},
"global": {
"misc": {
"metrics-addr": ":8080",
"metricSourceType": "accesslog",
"globalSidecarMode": "cluster"
}
},
"name": "lazyload-test",
"kind": "lazyload"
}
{"global":{"service":"app","istioNamespace":"istio-system","slimeNamespace":"mesh-operator","log":{"logLevel":"debug","klogLevel":5},"misc":{"aux-addr":":8081","enable-leader-election":"off","globalSidecarMode":"cluster","logSourcePort":":8083","metricSourceType":"accesslog","metrics-addr":":8080"},"istioRev":"v2","strictRev":true},"name":"lazyload-v2","enable":true,"general":{"namespace":["default"],"wormholePort":["9080"]},"mode":1," …
```

Support yaml format module config

---

framework/bootstrap/config.go
framework/controllers/destinationrule_controller.go
framework/controllers/virtualservice_controller.go

1. StrictRev is true, return true if 
- revision equals global.IstioRev
2. StrictRev is false, return true if one of 
- revision equals global.IstioRev
- revision is empty
- global.IstioRev is empty

Update revision matching logic

---

boot/helm-charts/slimeboot/templates/deployment.yaml
boot/helm-charts/slimeboot/values.yaml
framework/util/const.go

This commit is compatiable for new version envoyfilter through slime env `ENVOY_FILTER_NAME_LEGACY`. Default value is `v2`, can be overwriten through `spec.env`, like this
```yaml
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
name: plugin
namespace: mesh-operator
spec:
module:
- name: plugin
enable: true
env:
- name: ENVOY_FILTER_NAME_LEGACY
value: v1
// ...
```
Support for assigning different values for 3 variables, as below.
- Envoy_Ratelimit: v1 `envoy.ratelimit`, v2 `envoy.filters.network.ratelimit`
- Envoy_Route: v1 `envoy.router`, v2 `envoy.filters.http.router`
- Envoy_HttpConnectionManager: v1 `envoy.http_connection_manager`, v2 `envoy.filters.network.http_connection_manager`

Support for choosing different envoy filter names

---

boot/helm-charts/slimeboot/templates/deployment.yaml
boot/helm-charts/slimeboot/values.yaml
doc/en/slime-boot.md
doc/zh/slime-boot.md

`probe-port` was previously only used for health check, so it was not exposed to the slime service. Now the port is also the address of the user-defined interfaces, so it is renamed to `aux-port` and added to the slime service.

Add aux-port on slime service

---

framework/controllers/virtualservice_controller.go
staging/src/slime.io/slime/modules/lazyload/charts/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/templates/namespace-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/controllers/update_resources.go

1.some invalid vs can cause vs controller panic, fix this problem
2.global-sidecar runs in privileged mode
3.global-sidecar supoorts istio version 1.7+ plugin name
4.lua plugin usage changed,due to compatibale with istio 1.7
5.global-sidecar supports customize pod annotations

Fix invalid vs panic and lazyload supports old istio version

---

staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

in the pr https://github.com/slime-io/plugin/pull/20, envoyplugin support to patch to `ROOT`，but we lost the feature due to commit https://github.com/slime-io/plugin/commit/0addaa94dd9d6c0faffcaff35004f2790833d610.

plugin: fix the bug that envoyplugin can't patch to ROOT

---

framework/model/config.go
staging/src/slime.io/slime/modules/plugin/controllers/envoyplugin_controller.go
staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go

some scenarios require pass-through of resource metadata, especially for labels, which can be used to indicate that multiple instances of different types of resources belong to the same group.
this pr provide an environment variable interface `SLIME_PASS_LBL_REG` to configure the labels that need to be passed through, using [the regular syntax of the golang standard library](https://github.com/google/re2/wiki/Syntax) to match the labels.
example:
```
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
name: plugin
namespace: mesh-operator
spec:
module:
- name: plugin
enable: true
env:
- name: SLIME_PASS_LBL_REG
value: "^need-pass"
// ...
```
and create a `envoyplugin` with labels:
```
apiVersion: microservice.slime.io/v1alpha1
kind: EnvoyPlugin
metadata:
labels:
need-pass/a: …
```

Plugin: passing labels to envoyfilter

---

staging/src/slime.io/slime/modules/lazyload/controllers/process.go

Lazyload generates sidecar with empty workloadSelector for service without label selector. This sidecar will match all services in the same namespace, which is not what we want. So ignore these special services now.

Lazyload: ignore services without label selector

---

framework/bootstrap/configcontroller.go

Endpoints without related service is common， like kube-system/kube-scheduler.kube-system.svc.cluster.local in k8s, and kube-system/k8s.io-minikube-hostpath in minikube cluster, so ignore these endpoints error log. Otherwise, there will be too many error logs.

framework: ignore ep without related svc error

---

staging/src/slime.io/slime/modules/lazyload/controllers/producer.go

When destination address in global-sidecar accesslog is ip, we should ignore rather than add ip to servicefence. Lazyload controller will generate a debug log, like `"Accesslog is default/ratings -> 192.168.100.100, in which the destination is not domain, skip"`.

lazyload: ignore situation when accesslog dest is ip

---

staging/src/slime.io/slime/modules/limiter/controllers/producer.go

this pr solve the problem as following
calculating the number of pods for a service, the non-running state pods are not skipped

limiter: skip not runing pods in average ratelimiter

---

staging/src/slime.io/slime/modules/limiter/controllers/process.go

this pr support passing labels  to envoyfilter when label matched the regex specified in deployment env
use:
add env in limiter deployment
```
- name: SLIME_PASS_LBL_REG
value: istio.*
```
The above configuration means that if the smartlimiter labels starts with `istio`, then the label will be passed through to envoyfilter

limiter: passing labels to envoyfilter

---

framework/bootstrap/config.go
framework/bootstrap/http.go
framework/model/module/module.go

In the previous version (see https://github.com/slime-io/slime/pull/134), we can add custom http handlers in module level, like `/plugin/test`, `lazyload/metrics`. The path always begins with the module name. Now we supports path redirect, so path (alias path) can be anything after we defined the module path (redirect path) like before. 
Use param `global.misc.pathRedirect`, which can contain more than one direct rules. The expression is `[alias path1]->[redirect path1],[alias path2]->[redirect path2],...[alias pathN]->[redirect pathN]`
```yaml
global:
log:
logLevel: debug
misc:
aux-addr: ":9091"
pathRedirect: "/pluginz->/plugin/test,/test->/plugin/test"
name: plugin
kind: plugin
```
Suppose plugin has a custom http handler on `/plugin/test`, then we have 2 more handlers, `/pluginz` and …

framework: supports for path redirect on aux server

---

framework/bootstrap/http.go
framework/model/module/module.go
framework/util/util.go

**refactor httpserver pathRedirects**
prev impl only supports add-handle in `module.InitManager` and limits the usage.
This refactor removes the restriction and upper modules can add handle at any time while the `pathRedirects` also works for that.
**module config support special AnyMessage**
In some cases the module may want to parse the raw config data in its own way rather than providing a certian pb type/obj.
So we add a special data type `AnyMessage` to indicates that.
use case:
```go
type Module struct {
config util.AnyMessage
}
func (m *Module) Config() proto.Message {
return &m.config
}
```

refactor httpserver pathRedirects and module config support special AnyMessage

---

framework/bootstrap/config.go
framework/bootstrap/http.go
framework/model/module/module.go

Some modules are more sensitive to endpoint ready, such as requiring upper-level business state ready to provide services to the public.
In the previous separate deployment mode, readiness was defined and handled by itself.
After bundle deployment, the readiness is taken over by the framework layer, which then requires the framework layer to provide a mechanism for the module to communicate the real ready state down.

add ReadyManager to Environment

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go
staging/src/slime.io/slime/modules/limiter/controllers/process.go

this pr optimize the problem as following:
before this, if you set multi route in SmartLimiter,  it will generate envoyfilter with disorder patch, then it will refresh envoyfilter at regular intervals 
we don't want these things to happen often
```yaml
metadata:
name: prod-gateway
namespace: gateway-system
spec:
gateway: true 
target:
direction: outbound
port: 80
route:
- a.test.com/r1 
- b.test.com/r1 
sets:
_base:
descriptor:
- action:
fill_interval:
seconds: 60
quota: "1"
strategy: global
workloadSelector:
gw_cluster: prod-gateway  
```

fix envoyfilter patch disorder when multi routes is specified

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go

resolve extra ef patches when multi route specified in gw
introduced by   https://github.com/slime-io/slime/commit/64089eda814138256e4fbdb09b1954dbb1c2e334
```yaml
metadata:
name: prod-gateway
namespace: gateway-system
spec:
gateway: true 
target:
direction: outbound
port: 80
route:
- a.test.com/r1 
sets:
_base:
descriptor:
- action:
fill_interval:
seconds: 1
quota: "1"
strategy: global
- action:
fill_interval:
seconds: 60
quota: "30"
strategy: global
workloadSelector:
gw_cluster: prod-gateway  
```
above smartlimiter will generate two pateches , obviously this is wrong
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
name: prod-gateway.default.ratelimit
namespace: …
```

limiter: fix extra patches in ef when multi route specified

---

install/init/crds-v1.yaml

this pr do two things:
- update crds version to `apiextensions.k8s.io/v1`
- add descriptor in crds and you can use `kubectl explain` to look for more info about crd

support crds version apiextensions.k8s.io/v1

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_filters.go
staging/src/slime.io/slime/modules/limiter/model/model.go

supprt empty workloadSelector, then the envoyfilter will apply to all enovy pods in the {{ .namespace }}
```yaml
metadata:
name: prod-gateway
namespace: gateway-v112
spec:
gateway: true  
sets:
_base:
descriptor:
- action:
fill_interval:
seconds: 60
quota: "3"
strategy: single
target:
direction: outbound
route:
- a.test.com:80/r1
#workloadSelector:
```

support empty workloadselector in smartlimiter when gw is true

---

framework/bootstrap/config.go
framework/bootstrap/configcontroller.go
staging/src/slime.io/slime/modules/lazyload/controllers/process.go
staging/src/slime.io/slime/modules/lazyload/controllers/servicefence_controller.go
staging/src/slime.io/slime/modules/limiter/controllers/process.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go
staging/src/slime.io/slime/modules/plugin/controllers/envoyplugin_controller.go
staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go

1. istioRev: determines the scope of management
usage
If a is set, then whatever b is
if istioRev is empty, then whatever strictRev  is true or false, slime will manage the all cr
```yaml
global:
istioRev: ""
```
if strictRev is true, slime will only manage the cr with labels  `istio.io/rev: istio-17` or `istio.io/rev: istio-112` 
```yaml
global:
istioRev: istio-17,istio-112
strictRev: true
```
if strictRev is false, slime will manage the cr with label  `istio.io/rev: istio-17` or `istio.io/rev: istio-112`  or cr without rev label
```yaml
global:
istioRev: istio-17,istio-112
strictRev: false
```
if strictRev is false and istioRev is empty, slime will manage the all cr
```yaml
global:
strictRev: false
```
2. slime will retrive config via configRev instead of  istioRev+configRev

use istioRev to manage cr's reconcile instead of istioRev and configRev

---

staging/src/slime.io/slime/modules/plugin/controllers/controllers.go
staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go
staging/src/slime.io/slime/modules/plugin/module/module.go

The reconcile from the refresh-plugins-affected-by-changed-secret logic is not called by controller runtime and thus it will still works when current instance switches to candidate/standby role and competes with the leader/primary instance.
Use the ability provided by the framework layer to sense the current instance role and execute this update process only when it is the primary role, while the standby role state only caches the sensed changes and executes a resync the next time (if any) it cuts to the primary use.

plugin module support leader role switch-over

---

staging/src/slime.io/slime/modules/limiter/controllers/process.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go
staging/src/slime.io/slime/modules/limiter/module/module.go

set  replicaCount and `enable-leader-election: "on"  ` to support leader election in limiter
```yaml
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
name: limiter
namespace: mesh-operator
spec:
replicaCount: 2
image:
pullPolicy: Always
repository: docker.io/slimeio/slime-limiter
tag:  xxxxxxxxx  ##真实镜像
module:
- name: limiter
kind: limiter
enable: true
general:
disableGlobalRateLimit: true
disableAdaptive: true
disableInsertGlobalRateLimit: true
global:
misc:
enable-leader-election: "on"  
log:
logLevel: info
configSources:
- address: ss:// 
```

limiter: support leader election

---

Makefile
bin/gen_module.sh
modules/example/install/samples/slimeboot_example.yaml
modules/example/module/module.go

Run `MODULE_NAME=foo make new-module` or `bash bin/gen_module.sh foo` to initialize a new module scaffold. After modifying the api, run `MODULES=foo make generate-module` to regenerate the code.

slime: support init new module from template

---

staging/src/slime.io/slime/modules/lazyload/cmd/proxy/main.go

> For security purposes, ports will only be automatically increased when auto managing. 
the proxy server started by global-sidecar should not be turned off due to https://github.com/slime-io/slime/pull/157.

global-sidecar: disable auto shutdown proxy server

---

docker/Dockerfile.build-tools

In order to use more interfaces directly, we upgrade go-control-plane to v0.11.0, for which the go version needs to be upgraded to 1.17.
specifically we introduce [QueryParameterMatcher in ](https://github.com/envoyproxy/go-control-plane/blob/fd73e3e0fadcc4c69759e862fa3ff48bb92ee633/envoy/config/route/v3/route_components.pb.go#L3631) to support
queryMatch in limiter,
releate pr https://github.com/slime-io/slime/pull/281

build-tools integrates docker(cli) for building and publishing

---

framework/model/metric/ticker_producer.go
staging/src/slime.io/slime/modules/limiter/controllers/envoy_filters.go
staging/src/slime.io/slime/modules/limiter/controllers/envoy_local_limit.go
staging/src/slime.io/slime/modules/limiter/controllers/process.go
staging/src/slime.io/slime/modules/limiter/controllers/producer.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go

support workloadSelector , the priority is  workloadSelector > name.namespace
the limiter rule will dispatch to pods which has labels  `app: productpage, env: test ` in same ns with SmartLimiter.
if SmartLimiter apply to istio root ns, it will match all pods in cluster with  `app: productpage, env: test `
```yaml
metadata:
name: productpage
namespace: default
spec:
workloadSelector:
app: productpage
env: test  
sets:
_base:
descriptor:
- action:
fill_interval:
seconds: 10
quota: "2"
strategy: "single"
target:
port: 9080
```

limiter: support workloadselector

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/httpclient.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go

meshregistry nacos source add new configuration `Username` and `Password` to access nacos server using authentication.
usage:
```
apiVersion: v1
data:
cfg: |
bundle:
modules:
- name: meshregistry
kind: meshregistry
enable: true
cfg_meshregistry: |
name: meshregistry
kind: meshregistry
enable: true
mode: BundleItem
general:
LEGACY:
MeshConfigFile: ""
RevCrds: ""
Mcp:
EnableIncPush: false
NacosSource:
Enabled: true
Address:
- "http://nacos-0.nacos-headless.default:8848"
- "http://nacos-1.nacos-headless.default:8848"
- "http://nacos-2.nacos-headless.default:8848"
Mode: polling
Username: nacos
Password: nacos
```

meshreg: nacos source support security access

---

framework/bootstrap/configcontroller.go
framework/bootstrap/k8s.go
framework/bootstrap/monitorcontroller.go
framework/model/module/module.go
modules/example/module/module.go
staging/src/slime.io/slime/modules/lazyload/module/module.go
staging/src/slime.io/slime/modules/limiter/module/module.go
staging/src/slime.io/slime/modules/meshregistry/module/module.go
staging/src/slime.io/slime/modules/plugin/module/module.go

use InitReady() to indicate whether the framework is ready
```go
type InitReady interface {
InitReady() bool
// InitReady() <-chan struct
}
type ConfigController interface {
viewstore.ViewerStore
RegisterEventHandler(kind resource.GroupVersionKind, handler func(resource.Config, resource.Config, Event))
Run(stop <-chan struct{})
InitReady
}
```
submodule can determine whether ready as following
```go
func (m *Module) Setup(opts module.ModuleOptions) error {
cbs := opts.InitCbs
cbs.AddStartup(func(ctx context.Context) {
go func() {
if env.ConfigController != nil {
env.WaitReady(env.ConfigController)
}
// Create the server for the discovery service.
registryServer, err := server.NewServer(&server.Args{
SlimeEnv:     opts.Env,
RegistryArgs: regArgs,
})
if err != nil {
log.Errorf("failed to …
```

framework: add initready and init method

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector.go

we get all instances registered in the registry, but in some cases need to filter some instances by its metadata, use the LabelSelector to achieve this.
We have introduced a new configuration item Selectors in the general configuration of source，which is a list of selectors that specify the set of service instances to be processed, configured in the same way as the [k8s labelselector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors).
e.g. filter instances with  `env=dev` in metadata
``` yaml
NacosSource:
Enabled: true
Address:
- "http://127.0.0.1:8848"
Mode: polling
EndpointSelectors:
- MatchExpressions:
- Key: env
Operator: NotIn
Values:
- "dev"
```
NOTE: only support **Nacos** registry now.

meshregistry: nacos source support filtering instance

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/httpclient.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go

Before we fetch the nacos service only in a specific namespace/group, which can be set in this way:
``` yaml
NacosSource:
Namespace: public
Group: DEFAULT_GROUP
```
Now we support fetching the nacos service in all group in all namespaces, which can be set in this way:
``` yaml
NacosSource:
AllNamespaces: true
```
When "AllNamespaces" is enabled, we merge instances with the same service name from different namespaces and groups into a single ServiceEntry.
We use the API `/nacos/v1/ns/catalog/services` for fetching all services in all groups in a specific namespace. This api, which we found in the nacos 1.4.x console, is not documented in the [nacos openAPI](https://nacos.io/zh-cn/docs/open-api.html) documentation, so we cannot guarantee that this feature is compatible with the latest …

nacos source support fetching instances from all namespaces

---

staging/src/slime.io/slime/modules/meshregistry/pkg/server/processing.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

1. `/dubboCallModel` -> new `/dubboCallModel` with `provideservices` field fulfilled and `/sidecarDubboCallModel` which retains the original semantic
2. both apis support `app` param to allow filtering data of specified app

meshregistry: split api dubboCallModel and support param `app`

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/cmd/proxy/controller.go
staging/src/slime.io/slime/modules/lazyload/cmd/proxy/main.go
staging/src/slime.io/slime/modules/lazyload/cmd/proxy/svcController.go
staging/src/slime.io/slime/modules/lazyload/pkg/proxy/cache.go
staging/src/slime.io/slime/modules/lazyload/pkg/proxy/http.go

For short domains, such as `reviews`
globao-sidecar's previous logic was to extend it to reviews.{{ns}} and then forward it
This mr modifies this logic:
If reviews.{{ns}} exists in the cluster, then extend it.
If it doesn't exist, then forward it as the original request domain

global-sidecar: fix non ns svc

---

framework/model/module/module.go
framework/util/util.go

Simplify the code
- AnyMessage only supports raw content in json format
- general config no longer supports unrecognized fields which means no longer supporting config in pb-bytes format

framework: util.AnyMessage impl JSONPBUnmarshaler

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

We create a mock serviceentry that contains all known dubbo ports and update it continuously.
This serviceentry is used in conjunction with special pockets of Sidecar resources on the istio side to achieve the goal of allowing dubbo workloads that are temporarily dependent on the relationship location to also get all dubbo listeners.

meshregistry: zk source add RefreshSidecarMockServiceEntry logic

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

fix panic in corner case: root `/dubbo` node does not exist

meshreg: fix panic of reclose ch in zk watching mode

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/server/processing.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/watching.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/serviceentry.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/model.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

changes:
1. refactor the merge-ports-to-mock-serviceentry logic in zk source into a standalone component `ServiceEntryMergePortMocker`;
2. use the `...Mocker` to add the same feature to other sources: `nacos` and `eureka`;
3. align the init-source code of sources;

meshregistry: sources support generating mock service which contains merged ports

---

boot/publish.sh
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml

懒加载需将首次请求转发只global-sidecar
但实际场景中，很多ipv4:port的请求也被转发到了global-sidecar，这样只会白白增加一跳
所以我们在兜底逻辑中增加一步，如果请求符合ipv4:port，将直接passthrough，不再兜底到global-sidecar

lazyload:passthrough ipv4:port

---

staging/src/slime.io/slime/modules/lazyload/controllers/update_resources.go

在bundle模式中，我们用mode字段指明子模块组织形式
```
- name: limiter
kind: limiter
enable: true
mode: BundleItem
```
在lazyload中我们需要读取slimeboot进行update操作，该流程中slimeboot使用的是自己构建的结构
导致无法反序列化，所以暂时在update过程中删除这一暂无使用的字段。
之后的解决方案是lazyalod update使用framework提供的slimeboot结构
todo: https://github.com/slime-io/slime/issues/323

fix: rm unused field which casued unable to deserialize slimeboot

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/httpclient.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/watching.go

For multiple nacos clusters, we aggregate instances based on service names
Usage:
``` yaml
LEGACY:
NacosSource:
Enabled: true
Servers:
- Address:
- "http://1.1.1.1:8848"
AllNamespaces: true
- Address:
- "http://2.2.2.2:8848"
- Address:
- "http://3.3.3.3:8848"
Namespace: ns1
Group: group1
Mode: polling
LEGACY:
NacosSource:
Enabled: true
Address:
- "http://1.1.1.1:8848"
AllNamespaces: true
Mode: polling
```

meshreg: support fetching instances from multiple nacos clusters

---

staging/src/slime.io/slime/modules/lazyload/cmd/proxy/main.go
staging/src/slime.io/slime/modules/lazyload/pkg/proxy/http.go

支持关闭 global sidecar中的svc controller
```
- name: DISABLE_SVC_CONTROLLER
value: "true"
```
没有 DISABLE_SVC_CONTROLLER 变量或者 值为false都表示，开启svc controller

global-sidecar: add env DISABLE_SVC_CONTROLLER

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go

At some point we need to regroup the instances that fetch from the registry, which means reassigning them to new `Service`. For this, we need a mechanism to customize the instance service name, then group the instances by the new service name.
We introduced the `ServiceNaming` field in the `SourceArgs` to configure to enable Rename&Regroup. A nonil `ServiceNaming` means enable.
The struct of `ServiceNaming` is 
``` go
type ServiceNameConverter struct {
Sep   string              `json:"Sep,omitempty"`
Items []ServiceNamingItem `json:"Items,omitempty"`
}
type ServiceNamingItem struct {
Kind  ServiceNameItemKind `json:"Kind,omitempty"`
Value string              `json:"Value,omitempty"`
}
```
Each `ServiceNamingItem` configure how a service name substring is generated, then using the `Seq` to …

meshreg: nacos source support custom instance service name

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go

Previously using the service name or [a custom service name](https://github.com/slime-io/slime/pull/330) as the only host for the generated `ServiceEntry`, additional hosts are now supported for the `ServiceEntry`.
Use `[]*ServiceHostAlias` to configure the original host and all aliases of the original host, if the original host is configured, the `Source` should append the aliases when convert a ServiceEntry .
**NOTE: only nacos source support for now**
---
usage:
the nacos service `foo.go` will be converted to a `ServiceEntry` with hosts `foo.go,bar.go`
``` yaml
LEGACY:
NacosSource:
Enabled: true
Address:
- "http://1.1.1.1:8848"
Mode: polling
ServiceHostAliases:
- Host: foo.go
Aliases:
- "bar.go" 
```

meshreg: nacos source support adding service host aliases

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector.go

In https://github.com/slime-io/slime/pull/295, we introduced the source-scoped endpoint selector, and in https://github.com/slime-io/slime/pull/306, we introduced the service-scoped endpoint selector. We require instances to satisfy both scope endpoint selectors, which has limited our capabilities in practice.
In fact, if a service has a service-scoped endpoint selector, it can be configured to include the requirements of a source-scoped endpoint selector. In this case, the source-scoped endpoint selector will exist as the default service-scoped endpoint selector if not specified, giving us more flexibility in configuring the default behavior.

meshreg: make the source scoped EndpointepSelector as the default service-scoped endpoint selector

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/watching.go

In meshreg, we convert the external registration service to ServiceEntry, and we provide an ENV interface [`SE_LABEL_SELECTOR_KEYS`](https://github.com/slime-io/slime/pull/338) for configuring the extraction of metadata from ep to SE metadata, which will take effect on all services and requires the cooperation of ep. 
this pr add  a config interface `ServiceAdditionalMetas`, which can add its own unique metadata to the specified service through configuration.
**NOTE: only nacos source support for now**
---
usage:
config meshregistry nacos source as below:
```
NacosSource:
Enabled: true
Address:
- "http://127.0.0.1:8848"
Mode: polling
ServiceAdditionalMetas:
foo.go:
Labels:
additional/app: foo
```
we get a SE as:
``` json
{
"type":"networking.istio.io/v1alpha3/ServiceEntry", …
```

meshreg: support for adding additional metadata to a serviceentry

---

staging/src/slime.io/slime/modules/limiter/controllers/process.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go
staging/src/slime.io/slime/modules/limiter/module/module.go

之前的reconcile逻辑是将对应的smartlimiter的namespace/name缓存至感兴趣列表
然后通过定时器（目前代码是30s的定时器），计算生成envoyfilter
这样的处理缺失实时性，所以本mr在reconcile中增加了对smartlimiter的实时计算
实时计算过程：
- 根据smartlimiter spec，构建queryMap
- 根据queryMap查询metric
> metric 结构是一个  smartlimiter meta info =>  []Result 的结构
> 大致记录的是这个 smartlimiter 对应服务的一些指标，如pods个数，对于复杂的prometheus 可能还包括 cpu sum 等指标
-  用查询的metric 刷新smartlimiter和envoyfiler (这里是和复用了定时任务的ConsumeMetric函数)，为了避免冲突，加了把锁

limiter: generate ef on time

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go

`SourceArgs` adds `InstanceMetaRelabel` field to configure how to relabel instance metadata. The source implementation needs to be able to map the original metadata `Key` in the instance to the `TargetKey`, using the value of the `Key` as the value of the `TargetKey` by default, and remapping the value of the `Key` to another value as the value of the `TargetKey` if necessary.  When the `TargetKey` already exists, it is possible to overwrite or skip this relabel according to the `Overwrite` parameter.
**Note:** pr provides an implementation for nacos source only.
---
examle:  
1. Use the value of `namingPrefix` in the service instance metadata to concatenate the original service name above as the service name of the converted SE;
2. If the metadata `namingPrefix` does not exist , use the …

meshreg: support relabeling metadata for nacos instance

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/watching.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/serviceentry.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

background:
1. for those services with out a explicit concept of `service port`,  we need to aggregate the whole ports of instances to service ports. For example: we have two ep 1.1.1.1:8080 and 2.2.2.2:8081. After aggregating the svc ports we get http-8080: 8080 and http-8081: 8081, each instance has one of the corresponding ports.
2. The istio side will extract the instance of the specified service port by: If no target port is specified and there is no instance port with the same name, the service port number is used directly as the instance port. This means that service port 8080 will get two instances 1.1.1.1:8080 and 2.2.2.2:8080. This is obviously not what we expected (the instance 2.2.2.2 is not listening on port 8080)
3. It leads to invalid instances in the corresponding cluster …

 meshregistry: apply extra service ports to endpoint ports and do code clean

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/serviceentry.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

1. 通过统一的参数svcPort和instancePortAsSvcPort来控制相关的业务行为，减少各个source内的各自定制实现，提高可维护性
* `svcPort`: 表示显式的svc port， 0值会被忽略；
* `instancePortAsSvcPort` 为true时会将实例端口聚合为服务端口；
实际`if svcPort != 0 && instancePortAsSvcPort` 时，会得到二者的并集作为最终的服务端口（列表）
2. 让eureka/nacos支持像dubbo 那样聚合实例端口为服务端口。 完善服务模型

meshregistry: align support of svcPort and instancePortAsSvcPort parameters for sources

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

when config meshregistry zk source with a k8s service, which recreated after slime has connected to, the zk will use the expired invalid service ip.
also: https://github.com/slime-io/go-zk/pull/1

meshreg: fix zk client to use expired local dns records

---

staging/src/slime.io/slime/modules/meshregistry/go.mod
staging/src/slime.io/slime/modules/meshregistry/go.sum
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

After `zk.Connect` returns the `conn` object, it connects to the zk server asynchronously. The connection may fail, and then we store a `conn` that cannot send a request.

meshreg: check the state of the zk after connect (hotfix)

---

boot/helm-charts/slimeboot/templates/deployment.yaml
doc/zh/slime-boot.md
framework/bootstrap/config.go
framework/model/module/module.go
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/model/const.go
staging/src/slime.io/slime/modules/lazyload/module/module.go

之前存在的问题是：懒加载开启多副本模式时，global-sidecar的accesslog会上报至svc:lazyload.mesh-operator
但service后挂在多个pods，其中只有一个是主，用于真正处理accesslog, 那么上报至非主pods的accesslog并不能被处理
本MR实现以下内容：
如果开启多副本，会额外创建一个svc, 其selector如下
```yaml
apiVersion: v1
kind: Service
metadata:
labels:
app: lazyload
name: lazyload-leader
namespace: mesh-operator
spec:
ports:
...
selector:
app: lazyload
slime.io/leader: "true"
sessionAffinity: None
type: ClusterIP
status:
loadBalancer: {}
```
成为主的pods会给自己加上label，并在退出时移除该labels
```yaml
slime.io/leader: "true"
```
而global-sidecar中remote accesslog server的地址为` lazyload-leader.mesh-operator`
这样就可以保证每次上报的accesslog都只会被主pods接收。

lazyload: report accesslog to leader

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/serviceentry.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/serviceentry_test.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/model.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/model_test.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

Fix the issue where `ServiceEntryWithMeta` is always judged as not deep-equal, because the new one always has a new timestamp.
https://github.com/slime-io/slime/blob/67380da4891d76f031130eac92b80d95dd0e1a29/staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go#L450-L463

meshreg: notify update only if config actually changes

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml

背景：懒加载将首次访问兜底到global-sidecar时，用lua插件方式给请求加上了 Slime-Source-Ns （即请求发起方所在ns）
但在大规模场景下，lua性能有所欠缺。
------
本次改动：envoy 在1.22以及之后(对应的istio应该是 1.14.1 / 1.13.5 / 1.12.8)，支持了从env获取变量，并添加到路由的功能
```yaml
request_headers_to_add:
- header:
key: "Slime-Source-Ns"
value: "%ENVIRONMENT(POD_NAMESPACE)%"
```
所以我们修改了默认行为 
只有设置了addEnvHeaderViaLua，才会采用lua方式获取头，
否者我们用 request_headers_to_add 方式添加 Slime-Source-Ns（如果不设置我们将会才用request_headers_to_add ）
**需要关注的是，只有在1.14.1后的版本才支持request_headers_to_add，对于不支持的版本用户需要设置addEnvHeaderViaLua**
------
采用request_headers_to_add方式，envoyfilter(to-global-sidecar)效果如下
```yaml
- applyTo: ROUTE_CONFIGURATION
match:
context: SIDECAR_OUTBOUND
routeConfiguration:
name: "9088"
patch:
operation: MERGE
value:
request_headers_to_add:
- append: true
header:
key: Slime-Orig-Dest
value: …
```

lazylaod:  support request_headers_to_add replace lua plugin to add headers

---

staging/src/slime.io/slime/modules/lazyload/controllers/producer.go

DownstreamDirectRemoteAddress always the physical peer, but DownstreamRemote Address is not when request has XFF headers. See document on https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage
Fix #367

Replace DownstreamRemoteAddress with DownstreamDirectRemoteAddress 

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml

我们之前支持了 dispatch 特性，即我们可以指定指定某些域名的路由到指定cluster
```yaml
module:
- name: lazyload
kind: lazyload
enable: true
general:
dispatches:
- name: fake
domains:
- "www.163.com"
- "*.slime.io"  
cluster: "PassthroughCluster"
disableIpv4Passthrough: false
autoPort: true
autoFence: true
defaultFence: true   
wormholePort:
- "9080"
```
上面slimeboot中描述，我们将www.163.com以及`*.slimeio`的流量直接透传
（修改slimeboot后需要重启slime才能生效）
但是后来支持的ipv4透传功能与dispatch功能有冲突。
------
本次提交使得以下逻辑正常运行：
符合dispatch的流量走passthrough
符合ipv4流量走passthrough
其余匹配不上的流量走兜底
------
需要补充说明的 dispatch 的domains 只支持
精确： `www.foo.com`
前缀： `foo.*`
后缀：`*.foo.com`

lazyload: fix dispatch before route to global-sidecar

---

staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

之前的实现中，必须在envoyplugin指定vhost name的全部信息（包括端口）
before:
```yaml
spec:
host:
- 163.com:80
```
该pr主要内容：当patch到 outbound 或 gateway时，如果vhostname 没有端口信息，那么就补上一个 ':*'
after:
```yaml
spec:
host:
- 163.com
```
result:
```yaml
- applyTo: VIRTUAL_HOST
match:
context: SIDECAR_OUTBOUND
routeConfiguration:
vhost:
name: 163.com:*
patch:
```
istiod 要做适当适配, 才能支持这个特性
不影响之前使用

plugin:support vhost name without port

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/client.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go

same as: https://github.com/slime-io/slime/pull/327
For multiple eureka clusters, we aggregate instances based on service names
Usage:
``` yaml
LEGACY:
EurekaSource:
Enabled: true
Servers:
- Address:  
- http://1.1.1.1/eureka
- Address:
- http://2.2.2.2/eureka
RefreshPeriod: 15s
LEGACY:
EurekaSource:
Enabled: true
Address:
- http://1.1.1.1/eureka
RefreshPeriod: 15s
```

meshreg: support fetching instances from multiple eureka clusters

---

staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

指定route patch插件时,可能存在host为空的情况
所以此时不需要添加 ':*'
相关pr: https://github.com/slime-io/slime/pull/383

plugin:skip port wildcard when plugin host is empty

---

framework/apis/config/v1alpha1/config.pb.go
framework/apis/config/v1alpha1/config.proto
framework/bootstrap/http.go
framework/util/log.go
framework/util/util.go

在 https://github.com/slime-io/slime/pull/386 中,  提供了参数动态修改 slime 的 istio/pkg/log
但是之前的实现没有区分scope，也就是全局都会修改
本次mr将提供scope级别的日志等级修改, **默认情况下，所有scope都是info日志**
以下方式将 istio/pkg/log 的scope xdsc和mcpc设置为warn，其余所有scope为info
````yaml
global:
log:
ilogLevel: default:info,xdsc:warn,mcpc:warn
````
或者通过只设置default:info 将所有scope都设置为info
````yaml
global:
log:
ilogLevel: default:info
````
也可以通过接口动态设置日志级别
```
curl  -XPOST 'podip:8081/log/ilog?xdsc:warn,mcpc:warn'
```

support setting istio/pkg/log scpoe level

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/cmd/envoyproxy/Dockerfile
staging/src/slime.io/slime/modules/lazyload/cmd/envoyproxy/proxy.yaml
staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go
staging/src/slime.io/slime/modules/lazyload/controllers/serviceentry_cache.go

lazyload using envoy as global sidecar to support h1/h2. See details on #373.
Close #373 
TODO:

lazyload using envoy as global sidecar to support h1/h2

---

staging/src/slime.io/slime/modules/lazyload/cmd/proxy/main.go
staging/src/slime.io/slime/modules/lazyload/pkg/proxy/http.go

提高场景兼容性： 当请求没带 orig dest header时，使用host中的port作为转发请求的目标端口 （而不是wormhole port）。 
同时留参数（env WORMHOLE_PORT_PRIOR_TO_HOST_PORT）来保留原来的行为（用于容灾代理而非懒加载场景）

lazyload proxy use port in host when no OrigDest header

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go

为meshregistry dubbo/zk source增加`SelfConsume`参数，用于场景： 特殊情况下可能dubbo应用会调用自己提供的服务，而这个依赖关系又没有上报到zk（consume信息）导致meshregistry无法拿到。
该参数设为`true`后，会自动把app提供的服务添加到自己的依赖关系中，也即生成的`Sidecar`资源中。

meshregistry: add zk/dubbo source arg SelfConsume

---

staging/src/slime.io/slime/modules/meshregistry/pkg/util/locality.go

fixed https://github.com/slime-io/slime/issues/404

fix bug for istio locality illegal characters

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml

之前的 `request_header_to_add` 加在了rc级别 [rc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto)
这就导致了给rc下的所有路由都加上了这些headers
而我们本意是只给发往 global-sidecar 的流量加上header
参考 [route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-route)

mv request_header_to_add to route level

---

staging/src/slime.io/slime/modules/meshregistry/go.mod
staging/src/slime.io/slime/modules/meshregistry/go.sum
staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/server/processing.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/model.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

**backgrounds**
- For instance filtering, we designed the interface based on the Kubernetes standard label selector. 
However, simply using labels to filter instances is not sufficient to cover all scenarios, such as filtering based on IP blacklists. Therefore, we need to extend the endpoint selector API to support more filtering configurations. 
- There are two levels of scope for endpoint selectors: source-scoped and service-scoped. 
In the previous API, we agreed that once an instance matches the service-scoped endpoint selector, the source-scoped endpoint selector will be automatically ignored. This convention results in a large amount of duplicate configuration and additional constraint merging calculations when there are many specialized service-scoped constraints and common …

meshreg: epselector supports instance ip blacklist

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector_test.go

In pr https://github.com/slime-io/slime/pull/414 we enhanced the `EndpointSelector` api to support filtering instance based on IP blacklist. However, the package source's use of the `EndpointSelector` is different from the `EndpointSelector` api, so adjust it to be consistent with the `EndpointSelector` api.

meshreg: fix the implementation logic of selector hook is inconsistent with the definition of ep selector api

---

staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/cluster-global-sidecar.yaml
staging/src/slime.io/slime/modules/lazyload/charts/global-sidecar/templates/namespace-global-sidecar.yaml

由于社区版本1.13以及之后会下发 stats-filter envoyfilter， 这影响了prometheus方式的lazyload获取指标
所以给global-sidecar加了 `ISTIO_META_ISTIO_VERSION: 999.0.0`, 表示不需要下发这些stats-filter至global-sidecar
---
如果懒加载采用accesslog方式，就不必加上 `ISTIO_META_ISTIO_VERSION: 999.0.0`

lazyload: remove ISTIO_META_ISTIO_VERSION from gs when accesslog is used

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/selector_test.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source_test.go

When no `EpSelector` is configured, a hook is generated by default that returns false, which causes all instances to be filtered out by default.

meshreg: fix always filtering instances when no epselector is configured

---

.gitignore
staging/src/slime.io/slime/modules/plugin/controllers/conversion.go
staging/src/slime.io/slime/modules/plugin/controllers/proto.go

使用方式如下：
```yaml
- enable: true
name: fault-injection
rider:
settings:
delay:
delaySwitch: true
delayTime: 3000
error:
errorSwitch: false
typeUrl: type.googleapis.com/proxy.filters.http.rider.v3alpha1.RouteFilterConfig
- enable: true
name: fault-injection
typeUrl: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.RoutePluginConfig
wasm:
settings:
blockRules:
- .*
caseInsensitive: false
rejectedCode: "422"
```
输出envoyfilter如下：
```yaml
- applyTo: HTTP_ROUTE
match:
context: SIDECAR_OUTBOUND
routeConfiguration:
vhost:
name: nsf-demo-stock-viewer-sidecar.skiff-nsfdemo-sidecar.svc.cluster.local:80
route:
name: myroute
patch:
operation: MERGE
value:
typedPerFilterConfig:
ns1.fault-injection.rider:
'@type': type.googleapis.com/udpa.type.v1.TypedStruct
type_url: …
```

plugin: envoyplugin support wasm/rider

---

staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go
staging/src/slime.io/slime/modules/meshregistry/pkg/util/cache/podCache.go

1. Fix meshreg's performance degradation:
in [mr388](https://github.com/slime-io/slime/pull/388) we fixed a bug that would cause the program to hang. However, in some scenarios (for example, providers or consumers nodes do not exist), the first watch for zk ep will fail, bypassing the retry backoff strategy, and frequent retries will eventually occupy a lot of CPU. 
2. boundary scene adaptation:
meshreg will collect pod information in the cluster and populate the pod label into the metadata of the service instance with the same IP as the pod according to the source configuration. However, in clusters, there may be situations where non-running pods are assigned IP addresses but are not recycled, causing the IP-based matching mechanism to be ineffective.

Optimize meshreg’s CPU usage and boundary scene adaptation

---

staging/src/slime.io/slime/modules/meshregistry/pkg/mcpoverxds/mcpcontroller.go
staging/src/slime.io/slime/modules/meshregistry/pkg/mcpoverxds/mcpstore.go

原来： 
1. convert中更新resourceversion然后Update；
2. 但event-update-config流程可能被不同source并发调用，特殊时序下可能导致 **先convert生成较低ver的后update**，从而导致 configstore中的configs的maxver不是单调递增的，从而可能出现 **以较大ver触发的推送中不包含较小ver的数据**；
修复： 在update中更新ver，保证configstore中的configs的maxver单调递增的，修复该问题。

meshreg: mv update-resource-version from convert func to McpConfigStore.Update to avoid possible race condition

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_global_limit.go

复杂场景下，给全局共享限流同时配置：header match 和 query match时
（先配置query match 再配置 query match）导致全局共享限流不生效

limiter: fix matching order problem

---

staging/src/slime.io/slime/modules/lazyload/controllers/service_cache.go

多个service选中同一个pods的场景下
其中一个服务对应endpoints的更新，将导致ip绑定的多个svc缓存清空（采用 delete + add 进行update操作）
导致只有一个service对应的sidecar被更新

lazyload: fix incorrect deletion behavior when pod relate to multi sevice

---

framework/monitoring/monitoring.go
staging/src/slime.io/slime/modules/meshregistry/pkg/mcpoverxds/mcpcontroller.go
staging/src/slime.io/slime/modules/meshregistry/pkg/monitoring/monitoring.go
staging/src/slime.io/slime/modules/meshregistry/pkg/monitoring/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/server/httpServer.go
staging/src/slime.io/slime/modules/meshregistry/pkg/server/processing.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/client.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/httpclient.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/sidecar.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

添加 meshreg 指标：
- slime_meshregistry_enabled_source： 当前启用的注册中心总数
- slime_meshregistry_mcp_push_count：当前实例向 istiod 推送的次数
- slime_meshregistry_ready_time：启用的注册中心 source 达到就绪状态的耗时
- slime_meshregistry_polling_time：轮训模式从注册中心完成一次全量服务数据同步的耗时分布，分注册中心
- slime_meshregistry_polling_count：轮训模式向注册中心执行的全量服务数据同步的次数，分注册中心
- slime_meshregistry_service_entry_{creation,deletion,update}：执行 se 创建、删除、更新的次数，分注册中心
- slime_meshregistry_service_entry_total：当前内存中保存的 se 的总数
- slime_meshregistry_sidecar_{creation,deletion,update}：执行 sidecar 创建、删除、更新的次数，分注册中心
- slime_meshregistry_sidecar_total：当前内存中保存的 sidecar 的总数
- slime_meshregistry_source_event_count：注册中心 source 产生的配置变更事件的次数，分注册中心、配置类型、事件类型
- slime_meshregistry_source_client_request_count：向注册中心发起的请求的次数，分注册中心

meshreg: add metrics

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

usage:
```yaml
ZookeeperSource:
SingleAppService: true # 此为前置需求，开启该特性才能让服务具有 application label
MethodLBServiceSelectors:
- matchLabels:
application: foo # 只开启该服务/app上的method-lb
```

meshregistry: zk source support arg SingleAppService,MethodLBServiceSelectors

---

.gitignore
staging/src/slime.io/slime/modules/plugin/controllers/conversion.go

对于一个plm插件:
```yaml
- enable: true
listenerType: Gateway
name: envoy.filters.http.cors.v3
port: 8080
typeUrl: type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
```
之前： typeUrl不生效，因为typeUrl对于有效config才有意义所以原代码中要求`inline`不为空才能正确生成，也即上述内容需要加上
```yaml
inline: {}
```
才能正常工作。
之后： 对于该特殊场景（指定了typeUrl又并无实际内容需要设置），（不设置`inline: {}`就）可以正确生成对应配置
```yaml
operation: INSERT_BEFORE
value:
name: envoy.filters.http.cors.v3
typed_config:
'@type': type.googleapis.com/udpa.type.v1.TypedStruct
type_url: type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
value: {}
```

plugin: applyInlinePlugin supports non-empty typeURL and nil settings

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/eureka/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

变更内容：
1. 去掉`GatewayModel`/`NsfEureka` 等强业务含义的配置，改为更基础能力相关的配置项
本PR只完成eureka部分，其他source待后续PR。
为平滑升级，这两个字段暂时deprecate，在代码中做了转换。 待使用者都迁移完毕后可以彻底删除这两个配置
2. 对（eureka） conversion 部分代码进行重构，将convert逻辑收敛，以支撑1

meshreg: deprecate eurekasource NsfEureka and GatewayModel and refactor to decouple with them

---

framework/util/set.go
go.work
go.work.sum
staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/polling.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/watching.go

支持对 zk(dubbo) 服务的推空保护，该功能开启后会忽略掉广义上的服务下线事件：
- 实例清空。当 `providers` 目录下实例出现从 `n` 到 `0` 的变化时，zk 不会处理该变化，对应 interface 转换出的 se 将保持不变，直到下一次的有实例上线。
- Interface 下线。当对应 interface 目录在 zk 中被删除时，对应 interface 转换出的 se 将保持不变，直到下一次该 interface 被重新注册，且存在可用实例。
该功能仅适用于特定的场景，确认开启前请根据具体环境信息评估风险。
使用说明：
``` yaml
ZookeeperSource:
EnableEmptyProtection: true
```

meshreg: zk source support empty value protection

---

staging/src/slime.io/slime/modules/meshregistry/pkg/bootstrap/args.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/nacos/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/source.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/source_test.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/conversion.go
staging/src/slime.io/slime/modules/meshregistry/pkg/source/zookeeper/source.go

This PR introduces the `CreatedWithValue` in the `InstanceMetaRelabel` API, enabling the addition of extra metadata pairs for instances. Additionally, it implements support for the `InstanceMetaRelabel` API on the zk source.
for example：
``` yaml
ZookeeperSource:
InstanceMetaRelabel:
Items:
- Key: foo
TargetKey: foo
CreatedWithValue: "bar"
hello: world
hello: world
foo: bar
```

meshreg: enhance InstanceMetaRelabel to support adding new KV and add zk support for it

---

staging/src/slime.io/slime/modules/limiter/controllers/envoy_global_limit.go
staging/src/slime.io/slime/modules/limiter/controllers/producer.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller.go
staging/src/slime.io/slime/modules/limiter/controllers/smartlimiter_controller_test.go
staging/src/slime.io/slime/modules/limiter/controllers/suite_test.go
staging/src/slime.io/slime/modules/limiter/controllers/testdata/limit_by_method.local.ef.expect.yaml
staging/src/slime.io/slime/modules/limiter/controllers/testdata/limit_outbound_with_mismatch_selector.local.ef.expect.yaml
staging/src/slime.io/slime/modules/limiter/controllers/testdata/limit_outbound_with_mismatch_selector.local.yaml

#432 引入基于 workload 的均分限流时，移除了对于出方向流量场景时，不强制要求 workload 匹配的支持，无法适配 vm 场景。该提交不影响均分限流的基础上，用于找回 #432 之前版本对于 vm 场景的支持。

limiter: generate ef with workload selectror miss match pod for outbound or gateway
